CREATE TABLE S_AUTHORITY_USER (
ID INT NOT NULL
, CODE VARCHAR(100) NOT NULL
, NICK_NAME VARCHAR(255) NOT NULL
, PASSWORD VARCHAR(30) NOT NULL
, ROLE_CODE VARCHAR(100) NOT NULL
, UNIQUE UQ_S_AUTHORITY_USER_1 (CODE)
, PRIMARY KEY (ID)
, CONSTRAINT FK_S_AUTHORITY_USER_1 FOREIGN KEY (ROLE_CODE)
REFERENCES S_AUTHORITY_ROLE (CODE)
);

CREATE TABLE S_AUTHORITY_ROLE (
ID INT NOT NULL
, NAME VARCHAR(255) NOT NULL
, CODE VARCHAR(100) NOT NULL
, UNIQUE UQ_S_AUTHORITY_ROLE_1 (CODE)
, PRIMARY KEY (ID)
);

CREATE TABLE S_AUTHORITY_RESOURCE (
ID INT NOT NULL
, RTYPE INT NOT NULL
, CODE VARCHAR(100) NOT NULL
, UNIQUE UQ_S_AUTHORITY_RESOURCE_1 (RTYPE, CODE)
, PRIMARY KEY (ID)
);

CREATE TABLE S_AUTHORITY_ROLE_RESOURCE (
ROLE_ID INT NOT NULL
, RESOURCE_ID INT NOT NULL
, PRIMARY KEY (ROLE_ID, RESOURCE_ID)
, CONSTRAINT FK_S_AUTHORITY_ROLE_RESOURCE_1 FOREIGN KEY (RESOURCE_ID)
REFERENCES S_AUTHORITY_RESOURCE (ID)
, CONSTRAINT FK_S_AUTHORITY_ROLE_RESOURCE_2 FOREIGN KEY (ROLE_ID)
REFERENCES S_AUTHORITY_ROLE (ID)
);
