CREATE TABLE C_TEST_CONTACT (
	ID INT NOT NULL AUTO_INCREMENT
	, NAME VARCHAR(100) NOT NULL
	, PRIMARY KEY (ID)
);


CREATE TABLE C_TEST_PHONE (
	ID INT NOT NULL AUTO_INCREMENT
	, PTYPE VARCHAR(100) NOT NULL
	, NUMBER VARCHAR(100) NOT NULL
	, OWNER_ID INT NOT NULL
	, PRIMARY KEY (ID)
	, CONSTRAINT FK_C_TEST_PHONE_1 FOREIGN KEY (OWNER_ID)
REFERENCES C_TEST_CONTACT (ID)
);

CREATE TABLE C_TEST_HOBBY (
	ID INT NOT NULL AUTO_INCREMENT
	, NAME VARCHAR(100) NOT NULL
	, PRIMARY KEY (ID)
);

CREATE TABLE C_TEST_CONTACT_HOBBY (
	CONTACT_ID INT NOT NULL
	, HOBBY_ID INT NOT NULL
	, PRIMARY KEY (CONTACT_ID, HOBBY_ID)
	, CONSTRAINT FK_C_TEST_CONTACT_HOBBY_1 FOREIGN KEY (CONTACT_ID)
REFERENCES C_TEST_CONTACT (ID)
	, CONSTRAINT FK_C_TEST_CONTACT_HOBBY_2 FOREIGN KEY (HOBBY_ID)
REFERENCES C_TEST_HOBBY (ID)
);
